### ISSUE TITLE
After clicking the watching with me option is it normal for her to NOT look at the other browser? As in she just stares directly at you like normal

### ISSUE THREAD

**Issue by Envislon** [geneTechnician/watch-things-with-monika#1]
Dumb question but I'll ask anyways, to explain it more thoroughly I meant it as in she just looks straight at the screen when we're not talking with her, I see other people's screenshots have her look over to the side or at least where the video is when it's playing. I use Opera GX so it could be a browser thing?

**Comment by geneTechnician** [comment]
This submod takes advantage of Monika's eyes following the player's mouse (after around 400 affection). Are you placing your mouse on the browser side so she looks in that direction?

**Comment by Envislon** [comment]
Oh my mistake then, I haven't reached around 400 affection yet so thats probably why. There wasn't an instruction on how this works so my bad, you can just close the issue now.
